ARG PYTHON_VERSION="3.6"
FROM python:${PYTHON_VERSION} AS builder

apt-get install build-essential python-dev libxml2 libxml2-dev zlib1g-dev
pip3 install pynsett

ADD pynsett/ /usr/local/

ENV PORT="4001"
EXPOSE ${PORT}

CMD ["python -m usr.local.pynsett.server.server"]